name: prod

volumes:
  postgres_data: 
  postgres_data_backups: 
  pgadmin: 
  media:

services:
  postgres:
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    image: postgres
    restart: unless-stopped
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_data_backups:/backups
    env_file:
      - ./envvar/prod/.postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    env_file:
      - ./envvar/prod/.pgadmin
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
        restart: true

  django-web:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    container_name: django-docker
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    volumes:
      - media:/app/media
    env_file:
      - ./envvar/prod/.django
      - ./envvar/prod/.postgres

  frontend-proxy:
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      django-web:
        condition: service_started
        restart: true
    ports:
      - "8001:80"
    volumes:
      - ./compose/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - media:/usr/share/nginx/media:ro
