# Generated by Django 5.2.4 on 2025-07-29 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iconClass', models.CharField(max_length=50)),
                ('styleClass', models.CharField(max_length=50)),
                ('messagehead', models.CharField(max_length=200)),
                ('messagehead_en', models.CharField(max_length=200, null=True)),
                ('messagehead_ar', models.CharField(max_length=200, null=True)),
                ('message', models.CharField(max_length=200)),
                ('message_en', models.CharField(max_length=200, null=True)),
                ('message_ar', models.CharField(max_length=200, null=True)),
                ('seen', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LastSentMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('reason', models.CharField(choices=[('ST', 'Stock')], max_length=5)),
                ('value', models.CharField(choices=[('SLU', 'Stock level up'), ('SLD', 'Stock level down')], max_length=5)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
